language: node_js
node_js:
- 7.9.0
before_script:
- mkdir conf
- cp ci/lambda-config.js conf
- npm install -g gulp
- npm install
script: gulp deploy
sudo: false
notifications:
  slack:
    secure: hecfbphxY8YOvrCMlumSVHB4uUMjUOnzDFxs+L8IgjlzKTVTE9uUVBSqgV0KrPboSKxZn9M+6l7mXNQJhJOdc1Pke/KFgT4/bSYU9dpokyVUKIXwuEmq6ycG/Jg2WXYTFslsBTu87MZAWsgv4XL7KKpigS6gR7i0IHAFXI2XpMf9hON1qLIk3tKdfBzC7ICViC86tetFA6WMdeYeFJ+w7yJ8uY2FHGMw5mfTS0obt3Ue35D+P3SHga2iAkr/l1UesIDZ6s3AOYe7rvVYYVHHSs8BNx7zBD/vK/cgzdHJNeVpE0daHDHTbRWkVINe9NX4mncowlfJeL7389dXyK1Ihj9J6pPOa1fT5eiqYKUg0ZJcFVphSRjKKc5zBE9TDS8aGI21oopXLLmc1deywHR8YvyDm95eLj8KiJl4uG55XnjAb64yuRZQnxwQzLTdqSd4QDEA6Bvmzr7KBr5AxTuUyzZ8WyOqHhGKFM/9aI/YCCFYbDeh1jHiofim1eqezfCOTmhg84kfX5OlzgxyLVXHzkoYfl/o/oKB+ORQc5cPoYtjl6ajDgi9tMYEuJJxm2kvv/jGlpF7S3q9Yrw1MHoEzT1gn6XEPSSiKxsrqjDUinrAzY3kwowoF1HmRHgC+SYHqZRBMjfaFFVxlUP4tdx7PQppYpXQA+/eyqJZIol6QYY=
